---
- name: Configure passwordless sudo for Jenkins operations
  hosts: app_servers
  gather_facts: no
  become: yes
  
  tasks:
    - name: Create sudoers.d directory if it doesn't exist
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'
    
    - name: Add passwordless sudo for app server users
      lineinfile:
        path: /etc/sudoers.d/jenkins-users
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'
        backup: yes
    
    - name: Verify sudo configuration
      command: "sudo -l -U {{ ansible_user }}"
      become: no
      register: sudo_check
      changed_when: false
    
    - name: Display sudo privileges
      debug:
        msg: "{{ sudo_check.stdout_lines }}"

# Run with: 
# ansible-playbook -i inventory.ini ansible-passwordless-sudo.yml