##output block
output content {
    value       = local_file.pet.content
    sensitive = false
    description = "Content of the pet file"
  
}
output "pet-name" {
  value       = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}